### ISSUE TITLE
Duplicate Flashcards In Struggling List

### ISSUE THREAD

**Issue by ZacharyDavidSaunders** [Zackazt/CompTIA-Aplus-Study-Practice#16]
We have a bug whereas there are duplicate flashcards in the struggling list. I am looking into this now

**Comment by portexe** [comment]
After reviewing the code for the Issue-#17 pull request, merge to master and see if the issue is still happening.

**Comment by ZacharyDavidSaunders** [comment]
Issue is no longer occurring
