### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ZacharyDavidSaunders** [Zackazt/CompTIA-Aplus-Study-Practice#6]
We need to update the README file to display new features in the release chart, add and anticipated release date (for the next upcoming version), and shrink to logo.

**Comment by ZacharyDavidSaunders** [comment]
Pull Request: https://github.com/Zackazt/CompTIA-Aplus-Study-Practice/pull/7

**Comment by ZacharyDavidSaunders** [comment]
@Zackazt,
Please code review this small change

**Comment by portexe** [comment]
Looks good. Merged, and closing this issue.
